volumes:
  bdsdata:
services:
  bdsd:
    build: ./
    hostname: bdsd
    restart: on-failure
    network_mode: host
    volumes:
      - ./:/usr/local/node_app
      - bdsdata:/data
    ports:
      - 3000:3000/tcp